// Automatically generated turning types

interface TurningGenericParams {
  pattern:
    | '0-0-modal'
    | '0-0-to-0-1';
  state:
    | '0-0/app'
    | '0-0/app/overlay'
    | '0-0/app/primary/procedures/team-id/create'
    | '0-0/app/primary/teams/default/procedures'
    | '0-0/app/primary/workbench'
    | '0-0/app/sidebar'
    | '0-0/app/sidebar/achievements'
    | '0-0/app/sidebar/idea'
    | '0-0/website/'
    | '0-0/website/login'
    | '0-0/website/sign-up/complete-user-profile'
    | '0-0/website/sign-up/create-account'
    | '0-0/website/sign-up/create-account/password-form'
    | '0-0/website/sign-up/create-organization'
    | '0-1/website/join'
    | 'context:0-0'
    | 'context:0-1'
    | 'modal-0-0:create-task'
    | 'modal-0-0:create-task:procedure-selected'
    | 'modal-0-0:invite-user'
    | 'modal-0-1:placeholder'
    | 'navigation-block-0-0:procedure-changed'
    | 'navigation-block-0-1:placeholder'
    | 'organization-0:created'
    | 'organization-0:join-link-generated'
    | 'procedure-0-simple:created'
    | 'procedure-0-simple:creating'
    | 'user-0-0:logged-in'
    | 'user-0-0:organization-selected'
    | 'user-0-0:registered'
    | 'user-0-1:logged-in'
    | 'user-0-1:organization-selected'
    | 'user-0-1:pending-join'
    | 'user-0-1:registered';
  statePattern:
    | '0-*/*'
    | '0-*/**'
    | '0-*/app/*'
    | '0-*/app/**'
    | '0-*/app/primary/*'
    | '0-*/app/primary/**'
    | '0-*/app/primary/procedures/*'
    | '0-*/app/primary/procedures/**'
    | '0-*/app/primary/procedures/team-id/*'
    | '0-*/app/primary/procedures/team-id/**'
    | '0-*/app/primary/procedures/team-id{,/**}'
    | '0-*/app/primary/procedures{,/**}'
    | '0-*/app/primary/teams/*'
    | '0-*/app/primary/teams/**'
    | '0-*/app/primary/teams/default/*'
    | '0-*/app/primary/teams/default/**'
    | '0-*/app/primary/teams/default{,/**}'
    | '0-*/app/primary/teams{,/**}'
    | '0-*/app/primary{,/**}'
    | '0-*/app/sidebar/*'
    | '0-*/app/sidebar/**'
    | '0-*/app/sidebar{,/**}'
    | '0-*/app{,/**}'
    | '0-*/website/*'
    | '0-*/website/**'
    | '0-*/website/sign-up/*'
    | '0-*/website/sign-up/**'
    | '0-*/website/sign-up/create-account/*'
    | '0-*/website/sign-up/create-account/**'
    | '0-*/website/sign-up/create-account{,/**}'
    | '0-*/website/sign-up{,/**}'
    | '0-*/website{,/**}'
    | '0-*{,/**}'
    | '0-0/*'
    | '0-0/**'
    | '0-0/app'
    | '0-0/app/*'
    | '0-0/app/**'
    | '0-0/app/overlay'
    | '0-0/app/primary/*'
    | '0-0/app/primary/**'
    | '0-0/app/primary/procedures/*'
    | '0-0/app/primary/procedures/**'
    | '0-0/app/primary/procedures/team-id/*'
    | '0-0/app/primary/procedures/team-id/**'
    | '0-0/app/primary/procedures/team-id/create'
    | '0-0/app/primary/procedures/team-id{,/**}'
    | '0-0/app/primary/procedures{,/**}'
    | '0-0/app/primary/teams/*'
    | '0-0/app/primary/teams/**'
    | '0-0/app/primary/teams/default/*'
    | '0-0/app/primary/teams/default/**'
    | '0-0/app/primary/teams/default/procedures'
    | '0-0/app/primary/teams/default{,/**}'
    | '0-0/app/primary/teams{,/**}'
    | '0-0/app/primary/workbench'
    | '0-0/app/primary{,/**}'
    | '0-0/app/sidebar'
    | '0-0/app/sidebar/*'
    | '0-0/app/sidebar/**'
    | '0-0/app/sidebar/achievements'
    | '0-0/app/sidebar/idea'
    | '0-0/app/sidebar{,/**}'
    | '0-0/app{,/**}'
    | '0-0/website/'
    | '0-0/website/*'
    | '0-0/website/**'
    | '0-0/website/login'
    | '0-0/website/sign-up/*'
    | '0-0/website/sign-up/**'
    | '0-0/website/sign-up/complete-user-profile'
    | '0-0/website/sign-up/create-account'
    | '0-0/website/sign-up/create-account/*'
    | '0-0/website/sign-up/create-account/**'
    | '0-0/website/sign-up/create-account/password-form'
    | '0-0/website/sign-up/create-account{,/**}'
    | '0-0/website/sign-up/create-organization'
    | '0-0/website/sign-up{,/**}'
    | '0-0/website{,/**}'
    | '0-0{,/**}'
    | '0-1/*'
    | '0-1/**'
    | '0-1/website/*'
    | '0-1/website/**'
    | '0-1/website/join'
    | '0-1/website{,/**}'
    | '0-1{,/**}'
    | 'context:*'
    | 'context:**'
    | 'context:0-0'
    | 'context:0-1'
    | 'context{,:**}'
    | 'modal-0-*:*'
    | 'modal-0-*:**'
    | 'modal-0-*:create-task:*'
    | 'modal-0-*:create-task:**'
    | 'modal-0-*:create-task{,:**}'
    | 'modal-0-*{,:**}'
    | 'modal-0-0:*'
    | 'modal-0-0:**'
    | 'modal-0-0:create-task'
    | 'modal-0-0:create-task:*'
    | 'modal-0-0:create-task:**'
    | 'modal-0-0:create-task:procedure-selected'
    | 'modal-0-0:create-task{,:**}'
    | 'modal-0-0:invite-user'
    | 'modal-0-0{,:**}'
    | 'modal-0-1:*'
    | 'modal-0-1:**'
    | 'modal-0-1:placeholder'
    | 'modal-0-1{,:**}'
    | 'navigation-block-0-*:*'
    | 'navigation-block-0-*:**'
    | 'navigation-block-0-*{,:**}'
    | 'navigation-block-0-0:*'
    | 'navigation-block-0-0:**'
    | 'navigation-block-0-0:procedure-changed'
    | 'navigation-block-0-0{,:**}'
    | 'navigation-block-0-1:*'
    | 'navigation-block-0-1:**'
    | 'navigation-block-0-1:placeholder'
    | 'navigation-block-0-1{,:**}'
    | 'organization-*:*'
    | 'organization-*:**'
    | 'organization-*{,:**}'
    | 'organization-0:*'
    | 'organization-0:**'
    | 'organization-0:created'
    | 'organization-0:join-link-generated'
    | 'organization-0{,:**}'
    | 'procedure-*-simple:*'
    | 'procedure-*-simple:**'
    | 'procedure-*-simple{,:**}'
    | 'procedure-0-simple:*'
    | 'procedure-0-simple:**'
    | 'procedure-0-simple:created'
    | 'procedure-0-simple:creating'
    | 'procedure-0-simple{,:**}'
    | 'user-0-*:*'
    | 'user-0-*:**'
    | 'user-0-*{,:**}'
    | 'user-0-0:*'
    | 'user-0-0:**'
    | 'user-0-0:logged-in'
    | 'user-0-0:organization-selected'
    | 'user-0-0:registered'
    | 'user-0-0{,:**}'
    | 'user-0-1:*'
    | 'user-0-1:**'
    | 'user-0-1:logged-in'
    | 'user-0-1:organization-selected'
    | 'user-0-1:pending-join'
    | 'user-0-1:registered'
    | 'user-0-1{,:**}';
  initializeAlias:
    | 'goto home page'
    | 'goto home page (user A not registered)'
    | 'goto home page (user A registered)';
  transitionAlias:
    | 'transit to workbench'
    | 'click app logout link'
    | 'click login button on home page'
    | 'submit login form'
    | 'click sign-up button on home page'
    | 'fill mobile to create account'
    | 'submit form to create account'
    | 'create organization'
    | 'complete user profile';
}
